import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {materialize} from '../src/history.mjs';
import {buildFixturePackage,inspectPackage} from '../src/package.mjs';
import {readZip,writeZip,LIMITS} from '../src/zip.mjs';
import {parse,canonical,sha} from '../src/strict.mjs';
import {Journal} from '../src/journal.mjs';
import {Service} from '../src/service.mjs';
import {readBounded,publish} from '../src/fs.mjs';
const repo=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const fixture=()=>JSON.parse(fs.readFileSync(path.join(repo,'fixtures/conversation.json')));
const pkg=()=>buildFixturePackage(fixture(),'first');
const code=c=>e=>e.code===c;
function sandbox(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'threadport-test-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return root;}
function journal(t){const root=sandbox(t),j=new Journal(root);t.after(()=>{try{j.close();}catch{}});return j;}
function setup(j,kind='fixture_export'){const p=j.prepare(kind,pkg());return {p,a:j.approve(p.planId,p.planDigest)};}
test('boundary excludes every post-boundary byte in STORE package and every entry',()=>{
 const s=fixture(),original=canonical(s),b=buildFixturePackage(s,'first');assert.equal(b.includes('PRIVATE_AFTER_BOUNDARY'),false);const files=readZip(b);for(const bytes of files.values())assert.equal(bytes.includes('PRIVATE_AFTER_BOUNDARY'),false);
 assert.equal(canonical(s),original);assert.equal(inspectPackage(b).recordCount,5);assert.ok(files.get('history/records.jsonl').includes('PUBLIC_TOOL'));assert.equal(inspectPackage(b).nativeExecutable,false);
});
test('appending later source turns changes neither bounded records nor prefix digest',()=>{const s=fixture(),a=materialize(s,'first');s.turns.push({id:'later',status:'completed',items:[]});assert.deepEqual(materialize(s,'first'),a);});
test('boundary missing, duplicate, in progress and interrupted rejected',()=>{assert.throws(()=>materialize(fixture(),'absent'),code('BOUNDARY_INVALID'));for(const status of ['in_progress','interrupted']){const s=fixture();s.turns[0].status=status;assert.throws(()=>materialize(s,'first'),code('BOUNDARY_INVALID'));}const s=fixture();s.turns[1].id='first';assert.throws(()=>materialize(s,'first'),code('BOUNDARY_INVALID'));});
test('orphan tool output rejected',()=>{const s=fixture();s.turns[0].items.splice(1,1);assert.throws(()=>materialize(s,'first'),code('TOOL_PAIR_INVALID'));});
test('missing tool output cannot be repaired by later turn',()=>{const s=fixture();const result=s.turns[0].items.splice(2,1)[0];s.turns[1].items.push(result);assert.throws(()=>materialize(s,'first'),code('TOOL_PAIR_INVALID'));});
test('duplicate call/result and reversed result rejected',()=>{for(const mode of ['call','result','reverse']){const s=fixture();if(mode==='reverse')[s.turns[0].items[1],s.turns[0].items[2]]=[s.turns[0].items[2],s.turns[0].items[1]];else{const x=structuredClone(s.turns[0].items[mode==='call'?1:2]);x.id='extra';s.turns[0].items.splice(3,0,x);}assert.throws(()=>materialize(s,'first'),code('TOOL_PAIR_INVALID'));}});
test('parallel tool IDs retain correct output associations',()=>{const s=fixture();const x=structuredClone(s.turns[0].items[1]);x.id='call_two';x.payload.callAlias='lookup_two';const y=structuredClone(s.turns[0].items[2]);y.id='result_two';y.payload.callAlias='lookup_two';y.payload.outputText='SECOND';s.turns[0].items.splice(2,0,x,y);const h=materialize(s,'first');assert.equal(h.records[3].payload.callAlias,'c1');assert.equal(h.records[4].payload.callAlias,'c0');});
test('unknown source version, fields, reference lineage and record kinds fail closed',()=>{
 for(const mutate of [s=>s.schemaVersion='codex.rollout/1',s=>s.parent='/source/full.jsonl',s=>s.turns[0].items[0].kind='compaction',s=>s.turns[0].items[0].payload.extra='hidden']){const s=fixture();mutate(s);assert.throws(()=>materialize(s,'first'));}
});
test('system/developer roles and authority settings are never activated',()=>{for(const role of ['system','developer']){const s=fixture();s.turns[0].items[0].payload.role=role;assert.throws(()=>materialize(s,'first'));}const s=fixture();s.hooks=['run'];assert.throws(()=>materialize(s,'first'));});
test('output unavailable differs from observed empty output',()=>{const s=fixture();s.turns[0].items[2].payload.outputText=null;assert.throws(()=>materialize(s,'first'));s.turns[0].items[2].payload.outputText='';assert.equal(materialize(s,'first').records[2].payload.outputText,'');});
test('strict JSON rejects duplicate escaped keys, invalid UTF8, BOM, floats and depth overflow',()=>{for(const raw of ['{"a":1,"\\u0061":2}','\ufeff{}','{"a":1.2}','{"a":-0}','[1,]','"\\ud800"','['.repeat(34)+'0'+']'.repeat(34),Buffer.from([0xff])])assert.throws(()=>parse(raw));assert.equal(parse('{"a":1}').a,1);});
test('unsafe ZIP names rejected before writing or decompression',()=>{for(const p of ['../x.json','/x.json','a/../x.json','C:/x.json','a\\x.json','a//x.json','a\0.json'])assert.throws(()=>writeZip(new Map([[p,Buffer.from('{}')]])),code('UNSAFE_PATH'));});
test('duplicate and case-colliding ZIP entries rejected',()=>{const b=writeZip(new Map([['a.json',Buffer.from('{}')],['A.json',Buffer.from('{}')]]));assert.throws(()=>readZip(b),code('DUPLICATE_ENTRY'));});
test('archive symlink mode and local/central path mismatch rejected',()=>{const b=pkg(),end=b.length-22,center=b.readUInt32LE(end+16);const link=Buffer.from(b);link.writeUInt32LE((0o120777<<16)>>>0,center+38);assert.throws(()=>readZip(link),code('UNSAFE_PATH'));const mismatch=Buffer.from(b);mismatch[30]^=1;assert.throws(()=>readZip(mismatch),code('INVALID_ZIP'));});
test('archive entry limits, expansion ratio and uncompressed bounds enforced before inflate',()=>{const b=pkg(),center=b.readUInt32LE(b.length-6);const count=Buffer.from(b);count.writeUInt16LE(7,b.length-12);assert.throws(()=>readZip(count),code('PACKAGE_LIMIT'));const huge=Buffer.from(b);huge.writeUInt32LE(LIMITS.entry+1,center+24);assert.throws(()=>readZip(huge),code('PACKAGE_LIMIT'));const ratio=Buffer.from(b);ratio.writeUInt32LE(1,center+20);ratio.writeUInt32LE(101,center+24);assert.throws(()=>readZip(ratio),code('PACKAGE_LIMIT'));assert.throws(()=>readZip(Buffer.alloc(LIMITS.compressed+1)),code('PACKAGE_LIMIT'));});
test('trailing bytes, truncation, encryption and extra fields rejected',()=>{const b=pkg(),center=b.readUInt32LE(b.length-6);for(const kind of ['trailing','truncated','encryption','extra']){let v=Buffer.from(b);if(kind==='trailing')v=Buffer.concat([v,Buffer.from('x')]);if(kind==='truncated')v=v.subarray(0,-1);if(kind==='encryption')v.writeUInt16LE(1,center+8);if(kind==='extra')v.writeUInt16LE(1,center+30);assert.throws(()=>readZip(v));}});
test('CRC corruption rejected',()=>{const b=pkg();const pos=30+b.readUInt16LE(26);b[pos]^=1;assert.throws(()=>readZip(b),code('DIGEST_MISMATCH'));});
test('valid ZIP with tampered payload fails SHA check',()=>{const files=readZip(pkg());files.set('environment.json',Buffer.from('{"x":1}'));assert.throws(()=>inspectPackage(writeZip(files)),code('DIGEST_MISMATCH'));});
test('unlisted file, unknown manifest field/version and summary_only rejected',()=>{for(const kind of ['file','field','version','summary']){const files=readZip(pkg());if(kind==='file'){files.delete('environment.json');files.set('rogue.json',Buffer.from('{}'));}else{const m=JSON.parse(files.get('manifest.json'));if(kind==='field')m.approved=true;if(kind==='version')m.schemaVersion='threadport.package/2.0.0';if(kind==='summary')m.fidelity='summary_only';files.set('manifest.json',Buffer.from(canonical(m)));}assert.throws(()=>inspectPackage(writeZip(files)));}});
test('safe file reader rejects traversal, hidden inputs, symlinks and hardlinks',t=>{const root=sandbox(t);fs.writeFileSync(path.join(root,'source.json'),'{}');fs.symlinkSync('source.json',path.join(root,'link.json'));fs.linkSync(path.join(root,'source.json'),path.join(root,'hard.json'));for(const p of ['../a.json','.codex/auth.json','link.json','hard.json'])assert.throws(()=>readBounded(root,p),code('UNSAFE_PATH'));});
test('exclusive publication preserves existing files',t=>{const root=sandbox(t);publish(root,'x.json','FIRST');assert.throws(()=>publish(root,'x.json','SECOND'),code('IDEMPOTENCY_CONFLICT'));assert.equal(fs.readFileSync(path.join(root,'x.json'),'utf8'),'FIRST');});
test('durable versioned plan and actual fixture export survive journal reopen',t=>{const j=journal(t),{p,a}=setup(j);const op=j.apply(p.planId,a,'request_1234567890');assert.equal(op.state,'completed');assert.equal(op.nativeThreadRef,null);assert.equal(sha(fs.readFileSync(path.join(j.root,op.createdFile))),p.packageDigest);j.close();const reopened=new Journal(j.root);try{assert.equal(reopened.plan(p.planId).planDigest,p.planDigest);assert.equal(reopened.get(op.operationId).state,'completed');}finally{reopened.close();}});
test('approved true, forged or altered receipt cannot approve operations',t=>{const j=journal(t),{p,a}=setup(j);for(const receipt of [{approved:true},{...a,authTag:'00'.repeat(32)},{...a,target:'other'}])assert.throws(()=>j.apply(p.planId,receipt,'request_1234567890'),code('APPROVAL_INVALID'));});
test('stale approval, expired plan and changed staged bytes fail closed',t=>{const j=journal(t),{p,a}=setup(j);assert.throws(()=>j.apply(p.planId,a,'request_1234567890',{now:p.expiresAt+1}),code('APPROVAL_INVALID'));assert.throws(()=>j.approve(p.planId,'0'.repeat(64)),code('PLAN_STALE'));fs.appendFileSync(path.join(j.dir,'plans',p.planId+'.zip'),'changed');assert.throws(()=>j.apply(p.planId,a,'request_1234567890'),code('PLAN_STALE'));});
test('idempotency retry returns same operation; different digest conflicts; nonce cannot be reused',t=>{const j=journal(t),{p,a}=setup(j),op=j.apply(p.planId,a,'request_1234567890');assert.equal(j.apply(p.planId,a,'request_1234567890').operationId,op.operationId);const next=setup(j);assert.throws(()=>j.apply(next.p.planId,next.a,'request_1234567890'),code('IDEMPOTENCY_CONFLICT'));assert.throws(()=>j.apply(p.planId,a,'another_1234567890'),code('APPROVAL_INVALID'));});
test('crash after intent stays attention and never blindly creates on retry',t=>{const j=journal(t),{p,a}=setup(j);assert.throws(()=>j.apply(p.planId,a,'request_1234567890',{fault:'after_intent'}),code('SIMULATED_CRASH'));j.close();const reopened=new Journal(j.root);try{const op=reopened.apply(p.planId,a,'request_1234567890');assert.equal(op.state,'attention');assert.equal(fs.readdirSync(path.join(j.dir,'outputs')).length,0);}finally{reopened.close();}});
test('crash after durable fixture export reconciles exactly one output after reopen',t=>{const j=journal(t),{p,a}=setup(j);assert.throws(()=>j.apply(p.planId,a,'request_1234567890',{fault:'after_write'}),code('SIMULATED_CRASH'));j.close();const r=new Journal(j.root);try{const op=r.apply(p.planId,a,'request_1234567890');assert.equal(op.state,'completed');assert.equal(fs.readdirSync(path.join(j.dir,'outputs')).length,1);}finally{r.close();}});
test('partial fixture import reconciles owned receipt; tampered output remains attention',t=>{const j=journal(t),{p,a}=setup(j,'fixture_import');assert.throws(()=>j.apply(p.planId,a,'request_1234567890',{fault:'after_write'}),code('SIMULATED_CRASH'));const op=JSON.parse(j.db.prepare('SELECT body FROM operations').get().body);fs.writeFileSync(j.destination(op),'{}');assert.equal(j.reconcile(op.operationId).state,'attention');assert.equal(fs.readFileSync(j.destination(op),'utf8'),'{}');});
test('fixture import completion is a local receipt, not a native session',t=>{const j=journal(t),{p,a}=setup(j,'fixture_import');const op=j.apply(p.planId,a,'request_1234567890');assert.equal(op.state,'completed');const receipt=JSON.parse(fs.readFileSync(j.destination(op)));assert.equal(receipt.executionStarted,false);assert.equal(receipt.nativeThreadRef,null);});
test('all native API paths remain blocked even if caller supplies fake gate/approval fields',t=>{const service=new Service(sandbox(t));for(const name of ['port_create_export','port_apply_import']){assert.throws(()=>service.call(name,{planId:'x'}),code('GATE_UNVERIFIED'));assert.throws(()=>service.call(name,{planId:'x',approved:true,gates:{G0:'passed'}}));}});
test('inspection does not create state; preview persists only content-free diagnostic',t=>{const root=sandbox(t);fs.writeFileSync(path.join(root,'source.json'),JSON.stringify(fixture()));const service=new Service(root);const report=service.call('port_inspect_export',{sourcePath:'source.json',boundaryTurnId:'first'});assert.equal(report.nativeExecutable,false);assert.equal(fs.existsSync(path.join(root,'.threadport')),false);const saved=service.call('port_prepare_export',{sourcePath:'source.json',boundaryTurnId:'first'});const raw=fs.readFileSync(path.join(root,'.threadport/reports',saved.reportId+'.json'));assert.equal(raw.includes('PUBLIC_ALPHA'),false);assert.equal(raw.includes('PRIVATE_AFTER_BOUNDARY'),false);});
test('stdio MCP initialize, tools/list, call and hard gate work without sockets',t=>{
 const root=sandbox(t),messages=[{jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-03-26',capabilities:{},clientInfo:{name:'test',version:'1'}}},{jsonrpc:'2.0',method:'notifications/initialized'},{jsonrpc:'2.0',id:2,method:'tools/list'},{jsonrpc:'2.0',id:3,method:'tools/call',params:{name:'port_get_capabilities',arguments:{}}},{jsonrpc:'2.0',id:4,method:'tools/call',params:{name:'port_apply_import',arguments:{planId:'x'}}}];
 const r=spawnSync(process.execPath,[path.join(repo,'src/cli.mjs'),'--root',root,'mcp'],{input:messages.map(JSON.stringify).join('\n')+'\n',encoding:'utf8'});assert.equal(r.status,0,r.stderr);const out=r.stdout.trim().split('\n').map(JSON.parse);assert.equal(out.length,4);assert.ok(out[1].result.tools.length>=7);assert.equal(out[3].result.isError,true);assert.match(out[3].result.content[0].text,/GATE_UNVERIFIED/);assert.equal(fs.existsSync(path.join(root,'.threadport')),false);
});
test('stdio malformed and oversized input fail safely and terminate',t=>{const root=sandbox(t);for(const input of ['{"jsonrpc":"2.0","id":1,"id":2}\n','x'.repeat(65537)]){const r=spawnSync(process.execPath,[path.join(repo,'src/cli.mjs'),'--root',root,'mcp'],{input,encoding:'utf8',timeout:5000});assert.equal(r.status,0);assert.equal(JSON.parse(r.stdout).error.code,-32700);}});
test('CLI native export returns exit 3; noninteractive approval fails',t=>{const root=sandbox(t);let r=spawnSync(process.execPath,[path.join(repo,'src/cli.mjs'),'--root',root,'export','x'],{encoding:'utf8'});assert.equal(r.status,3);assert.match(r.stderr,/GATE_UNVERIFIED/);r=spawnSync(process.execPath,[path.join(repo,'src/cli.mjs'),'--root',root,'fixture-approve','x'],{encoding:'utf8'});assert.equal(r.status,1);assert.match(r.stderr,/LOCAL_APPROVAL_REQUIRED/);});
function rehash(files){
 const m=JSON.parse(files.get('manifest.json'));
 for(const f of m.files){const b=files.get(f.path);f.byteLength=b.length;f.sha256=sha(b);}
 files.set('manifest.json',Buffer.from(canonical(m)));
 const c=JSON.parse(files.get('checksums.json'));for(const f of c.files){const b=files.get(f.path);f.byteLength=b.length;f.sha256=sha(b);}files.set('checksums.json',Buffer.from(canonical(c)));return writeZip(files);
}
test('self-consistent checksums cannot conceal invalid UTF8 in record stream',()=>{const files=readZip(pkg());const b=Buffer.from(files.get('history/records.jsonl'));const i=b.indexOf('PUBLIC_ALPHA');assert.ok(i>=0);b[i]=0xff;files.set('history/records.jsonl',b);assert.throws(()=>inspectPackage(rehash(files)),code('INVALID_JSON'));});
test('rehashed malicious boundary and tool mismatch still rejected',()=>{
 for(const kind of ['boundary','tool']){const files=readZip(pkg());if(kind==='boundary'){const m=JSON.parse(files.get('manifest.json'));m.boundary.turnAlias='private';files.set('manifest.json',Buffer.from(canonical(m)));}else{const records=files.get('history/records.jsonl').toString().trim().split('\n').map(JSON.parse);records[2].payload.callAlias='rogue';files.set('history/records.jsonl',Buffer.from(records.map(canonical).join('\n')+'\n'));}assert.throws(()=>inspectPackage(rehash(files)),code(kind==='boundary'?'BOUNDARY_INVALID':'TOOL_PAIR_INVALID'));}
});
test('rehashed environment hooks and index extra metadata rejected',()=>{for(const p of ['environment.json','history/index.json']){const files=readZip(pkg());const value=JSON.parse(files.get(p));value.hooks=['PRIVATE_AFTER_BOUNDARY'];files.set(p,Buffer.from(canonical(value)));assert.throws(()=>inspectPackage(rehash(files)));}});
test('journal unknown version and changed plan fields fail closed',t=>{const j=journal(t),{p}=setup(j);const changed={...p,revision:2};j.db.prepare('UPDATE plans SET body=? WHERE id=?').run(canonical(changed),p.planId);assert.throws(()=>j.plan(p.planId));j.db.exec('PRAGMA user_version=99');j.close();assert.throws(()=>new Journal(j.root),code('UNSUPPORTED_VERSION'));});
test('receipts from another local root cannot approve a plan',t=>{const a=journal(t),b=journal(t),first=setup(a),second=setup(b);assert.throws(()=>b.apply(second.p.planId,first.a,'request_1234567890'),code('APPROVAL_INVALID'));});
test('operation lookup does not initialize missing registry',t=>{const root=sandbox(t),service=new Service(root);assert.throws(()=>service.call('port_get_operation',{operationId:'missing'}),code('OPERATION_NOT_FOUND'));assert.equal(fs.existsSync(path.join(root,'.threadport')),false);});
test('historical source drafts and prior addendum remain byte-identical',()=>{for(const [p,h]of Object.entries({'docs/source/THREADPORT_DESIGN.md':'bb80d57d55cf4b0fa7bce836fc696730b8ab1ac0af78801c0222f17d2278869c','docs/source/THREADPORT_CONTRACTS.md':'a060dcf65554e31977d09d83b62b0fb2a4055a13ccf457a4dd59d6f8bfc557ac','docs/THREADPORT_IMPLEMENTATION_ADDENDUM.md':'91ba14a58a097555dd58720db1d953db58aa53e50504d5faa694d52e5c32e787'}))assert.equal(sha(fs.readFileSync(path.join(repo,p))),h);});
import {deflateRawSync} from 'node:zlib';
import {spawn} from 'node:child_process';
test('bounded DEFLATE branch decodes valid data and rejects trailing compressed bytes',()=>{
 const data=Buffer.from('hello zip '.repeat(5)),stored=writeZip(new Map([['a.json',data]])),compressed=deflateRawSync(data),nl=stored.readUInt16LE(26),oldCenter=stored.readUInt32LE(stored.length-6);
 const make=packed=>{const l=Buffer.from(stored.subarray(0,30+nl)),c=Buffer.from(stored.subarray(oldCenter,stored.length-22)),e=Buffer.from(stored.subarray(-22));l.writeUInt16LE(8,8);l.writeUInt32LE(packed.length,18);c.writeUInt16LE(8,10);c.writeUInt32LE(packed.length,20);e.writeUInt32LE(l.length+packed.length,16);return Buffer.concat([l,packed,c,e]);};
 assert.deepEqual(readZip(make(compressed)).get('a.json'),data);assert.throws(()=>readZip(make(Buffer.concat([compressed,Buffer.from('junk')]))),code('INVALID_ZIP'));
});
test('two processes using the same idempotency key create only one owned output',async t=>{
 const j=journal(t),{p,a}=setup(j);j.close();
 const moduleUrl=new URL('../src/journal.mjs',import.meta.url).href;
 const script=`import {Journal} from ${JSON.stringify(moduleUrl)};const j=new Journal(process.argv[1]);try{console.log(JSON.stringify(j.apply(process.argv[2],JSON.parse(process.argv[3]),'same_request_12345678')));}finally{j.close();}`;
 const launch=()=>new Promise((resolve,reject)=>{const child=spawn(process.execPath,['--input-type=module','-e',script,j.root,p.planId,JSON.stringify(a)],{stdio:['ignore','pipe','pipe']});let out='',err='';child.stdout.on('data',b=>out+=b);child.stderr.on('data',b=>err+=b);child.on('error',reject);child.on('close',status=>resolve({status,out,err}));});
 const results=await Promise.all([launch(),launch()]);for(const r of results)assert.equal(r.status,0,r.err);assert.equal(JSON.parse(results[0].out).operationId,JSON.parse(results[1].out).operationId);assert.equal(fs.readdirSync(path.join(j.dir,'outputs')).length,1);
});
test('process exit after output before completion is reconciled by new process',t=>{
 const j=journal(t),{p,a}=setup(j);j.close();
 const script=`import {Journal} from ${JSON.stringify(new URL('../src/journal.mjs',import.meta.url).href)};const j=new Journal(process.argv[1]);try{j.apply(process.argv[2],JSON.parse(process.argv[3]),'crash_request_12345',{fault:'after_write'});}catch{process.exit(23);}`;
 const child=spawnSync(process.execPath,['--input-type=module','-e',script,j.root,p.planId,JSON.stringify(a)],{encoding:'utf8'});assert.equal(child.status,23,child.stderr);
 const reopened=new Journal(j.root);try{assert.equal(reopened.apply(p.planId,a,'crash_request_12345').state,'completed');}finally{reopened.close();}
});
test('packaged manifest and runtime schema artifacts match',()=>{
 const m=JSON.parse(fs.readFileSync(path.join(repo,'.codex-plugin/plugin.json')));assert.equal(m.name,'threadport');assert.equal(m.mcpServers,'./.mcp.json');assert.ok(fs.existsSync(path.join(repo,'skills/threadport/SKILL.md')));
 const schema=JSON.parse(fs.readFileSync(path.join(repo,'schemas/source.schema.json')));assert.equal(schema.additionalProperties,false);assert.equal(schema.properties.schemaVersion.const,'threadport.synthetic-source/1.0.0');
});
test('replaced target directory inode invalidates a durable approval plan',t=>{
 const j=journal(t),{p}=setup(j),moved=j.root+'-moved';j.close();fs.renameSync(j.root,moved);t.after(()=>fs.rmSync(moved,{recursive:true,force:true}));fs.mkdirSync(j.root,{mode:0o700});fs.cpSync(path.join(moved,'.threadport'),path.join(j.root,'.threadport'),{recursive:true});
 for(const dir of ['', '/plans','/outputs','/sessions','/reports'])fs.chmodSync(path.join(j.root,'.threadport'+dir),0o700);
 const replacement=new Journal(j.root);try{assert.throws(()=>replacement.plan(p.planId),code('PLAN_STALE'));}finally{replacement.close();}
});
