import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';
import {parse,validate,obj,str,arr,literal} from '../src/strict.mjs';
const root=fileURLToPath(new URL('../',import.meta.url));
const m=parse(fs.readFileSync(path.join(root,'.codex-plugin/plugin.json')));
validate(obj({name:literal('threadport'),version:literal('0.1.0'),description:str(),author:obj({name:literal('RUVORA')}),skills:literal('./skills/'),mcpServers:literal('./.mcp.json'),interface:obj({displayName:str(),shortDescription:str(),longDescription:str(),developerName:str(),category:literal('Productivity'),capabilities:arr(str(),8),defaultPrompt:arr(str(128),3)})}),m);
if(path.basename(path.resolve(root))!==m.name)throw Error('Plugin root/name mismatch');
const config=parse(fs.readFileSync(path.join(root,'.mcp.json')));
validate(obj({mcpServers:obj({threadport:obj({command:literal('node'),args:arr(str(),4)})})}),config);
const expected=['${CODEX_PLUGIN_ROOT}/src/cli.mjs','--root','${CODEX_PLUGIN_ROOT}','mcp'];
if(JSON.stringify(config.mcpServers.threadport.args)!==JSON.stringify(expected))throw Error('Unexpected MCP configuration');
const skill=fs.readFileSync(path.join(root,'skills/threadport/SKILL.md'),'utf8');const front=skill.match(/^---\nname: ([a-z-]+)\ndescription: ([^\n]+)\n---\n/);
if(!front||front[1]!=='threadport'||!front[2].trim())throw Error('Invalid supported skill frontmatter subset');
for(const p of ['src/cli.mjs','README.md','docs/USAGE_KO.md','SECURITY.md'])if(!fs.statSync(path.join(root,p)).isFile())throw Error('Missing component');
if(JSON.stringify(m).includes('[TODO:'))throw Error('Placeholder manifest');
const r=spawnSync(process.execPath,config.mcpServers.threadport.args.map(s=>s.replaceAll('${CODEX_PLUGIN_ROOT}',root)),{input:JSON.stringify({jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-03-26'}})+'\n',encoding:'utf8',timeout:10000});
if(r.status!==0||JSON.parse(r.stdout).result?.serverInfo.name!=='ruvora-threadport')throw Error('Packaged stdio entry point failed');
console.log(JSON.stringify({valid:true,validator:'repository Node builtin profile validator',pluginName:m.name,version:m.version,manifest:true,skillFrontmatter:true,companionPaths:true,stdioInitializeExit:r.status,installationVerified:false,nativeG0:'unverified',nativeG3:'unverified'}));
